# Generated by Django 5.0.1 on 2024-01-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='moive',
            new_name='movie',
        ),
    ]
